spring.application.name=backend
spring.security.user.name=admin
spring.security.user.password=adminadmin

server.port=8080

app.data.settings-file=data/settings.json
app.data.log-file=data/app.log

frankfurter.api.url=https://api.frankfurter.dev/v1